services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5431:5432
    networks:
      - spring-book
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.3
    ports:
      - 8088:8088
    networks:
      - spring-book
    depends_on:
      - postgres
  bsn-front:
    container_name: bsn-front
    image: bsn/bsn-front:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-book
    depends_on:
      - bsn-api
networks:
  spring-book:
    driver: bridge

volumes:
  postgres:
    driver: local